### ISSUE TITLE
VagrantでWordpressを構築

### ISSUE THREAD

**Issue by RVIRUS0817** [muranaka-jun/menta#2]
## 要件

- [x] Vagrantは最新バージョン
- [x] CentOS7
- [x] php7.1(php-fpm) チューニング
- [x] Nginx/H2O https/リダイレクトの設定
- [x] MySQL 5.7 wordpressユーザーとDBの作成
- [x] Wordpress最新
- [x] IPではなく、バーチャルで名前解決

こちら構築お願いします。
@muranaka-jun

**Comment by RVIRUS0817** [comment]
```sh
RVIRUS@Adachin-mini > git br -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
  remotes/origin/menta
[~/git/RVIRUS0817/ansible_Mac]

```

**Comment by muranaka-jun** [comment]
'''
12:07:26 ~ $ vagrant -v
Vagrant 2.2.0
12:07:36 ~ $ 
'''

**Comment by muranaka-jun** [comment]
add : CentOS7.0 box 追加
参考ページ：https://qiita.com/RyochanUedasan/items/b1ff13bc39913cb5b561

'''
13:18:18 ~/Desktop $ vagrant box add centos7.0 https://github.com/tommy-muehle/puppet-vagrant-boxes/releases/download/1.1.0/centos-7.0-x86_64.box
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'centos7.0' (v0) for provider: 
    box: Downloading: https://github.com/tommy-muehle/puppet-vagrant-boxes/releases/download/1.1.0/centos-7.0-x86_64.box
    box: Download redirected to host: github-production-release-asset-2e65be.s3.amazonaws.com
==> box: Successfully added box 'centos7.0' (v0) for 'virtualbox'!
13:25:18 ~/Desktop $ 
'''

**Comment by muranaka-jun** [comment]
## 実施
**MySQL5.7インストール**
[root@localhost nkf-2.1.3]# mysql --version
mysql  Ver 14.14 Distrib 5.7.24, for Linux (x86_64) using  EditLine wrapper

**php7.1(php-fpm)インストール**
[root@localhost nkf-2.1.3]# php --version
PHP 7.1.23 (cli) (built: Oct 10 2018 12:11:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
[root@localhost nkf-2.1.3]# php -i | head
phpinfo()
PHP Version => 7.1.23

System => Linux localhost.localdomain 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64
Build Date => Oct 10 2018 12:10:38
Server API => Command Line Interface
Virtual Directory Support => disabled
Configuration File (php.ini) Path => /etc
Loaded Configuration File => /etc/php.ini
Scan this dir for additional .ini files => /etc/php.d

**Nginxインストール**
[root@localhost nkf-2.1.3]# nginx -V
nginx version: nginx/1.14.0
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) 
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -pie'
[root@localhost nkf-2.1.3]#

**Comment by muranaka-jun** [comment]
## 実施
wordpress最新版をサーバに入れる
※設定はまだ

[root@localhost nkf-2.1.3]# ls -l
合計 11724
-rw-r--r-- 1   1001 users         525 11月 22  2013 INSTALL
-rw-r--r-- 1   1001 users         634 11月 22  2013 INSTALL.j
-rw-r--r-- 1   1001 users         306 11月 22  2013 MANIFEST
-rw-r--r-- 1   1001 users        1710 11月 22  2013 Makefile
drwxr-xr-x 2   1001 users         106 11月  4 14:59 NKF.mod
-rw-r--r-- 1   1001 users        1066 11月 22  2013 config.h
-rwxr-xr-x 1   1001 users         454 11月 22  2013 dll.def
-rwxr-xr-x 1   1001 users         883 11月 22  2013 dll.rc
-rw-r--r-- 1 root   root      9292403  8月  3 11:52 latest-ja.tar.gz
-rw-r--r-- 1   1001 users         582 11月 22  2013 make_test.pl
-rwxr-xr-x 1 root   root       539984 11月  4 14:59 nkf
-rw-r--r-- 1   1001 users       14483 11月 22  2013 nkf.1
-rw-r--r-- 1   1001 users       22002 11月 22  2013 nkf.1j
-rw-r--r-- 1   1001 users      174141 11月 22  2013 nkf.c
-rw-r--r-- 1   1001 users       12549 11月 22  2013 nkf.doc
-rwxr-xr-x 1   1001 users        4251 11月 22  2013 nkf.h
-rwxr-xr-x 1   1001 users         965 11月 22  2013 nkf.mak
-rw-r--r-- 1 root   root       522760 11月  4 14:59 nkf.o
-rwxr-xr-x 1   1001 users          17 11月 22  2013 nkf32.c
-rwxr-xr-x 1   1001 users        3940 11月 22  2013 nkf32.h
-rw-r--r-- 1   1001 users       27448 11月 22  2013 nkf32dll.c
-rw-r--r-- 1   1001 users       62143 11月 22  2013 nkf_test.pl
-rw-r--r-- 1   1001 users        3015 11月 22  2013 test.pl
-rw-r--r-- 1   1001 users      842388 11月 22  2013 utf8tbl.c
-rw-r--r-- 1   1001 users        2802 11月 22  2013 utf8tbl.h
-rw-r--r-- 1 root   root       402080 11月  4 14:59 utf8tbl.o
-rwxr-xr-x 1   1001 users         835 11月 22  2013 version.rc
drwxr-xr-x 5 nobody nfsnobody    4096  8月  3 11:07 wordpress

**Comment by RVIRUS0817** [comment]
@muranaka-jun 
良いと思います！

**Comment by muranaka-jun** [comment]
@RVIRUS0817 
ありがとうございます！

**Comment by RVIRUS0817** [comment]
こちら設定ファイルなどどのように設定されたか確認したいです👍

**Comment by muranaka-jun** [comment]
### nginxの設定
```
# cat /etc/nginx/conf.d/default.conf
server {
    listen       80;
    server_name  localhost;
    root /var/www/html/sample.com;
    charset UTF-8;
    access_log  /var/log/nginx/sample.com.access.log  main;
    error_log /var/log/nginx/sample.com.error.log;

    location / {
        index  index.php index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    location ~ \.php$ {
        fastcgi_pass   unix:/var/run/php-fpm/php-fpm.sock;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }
}
```

### php-confの設定
以下変更箇所
```
修正前
listen = 127.0.0.1:9000
修正後
listen = /var/run/php-fpm.sock

修正前
user = apache 
修正後
user = nginx 

修正前
group = apache
修正後
group = nginx

修正前
;listen.owner = nobody
;listen.group = nobody
修正後
listen.owner = nginx
listen.group = nginx
```

### MySQL
データベースのみ作成、ユーザの作成はなし。
```
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
| wordpress          |
+--------------------+
5 rows in set (0.00 sec)

mysql>
```

他に何か確認したいものありますか？

**Comment by RVIRUS0817** [comment]
@muranaka-jun 
>nginxの設定
こちらSSL証明書の設定をして、httpからhttpsにリダイレクト設定してもらえますか？

>php-fpm
こちら簡単でいいのでチューニングをしてください。

>MySQL
こちらwordpressユーザを作って、権限等設定してください

**Comment by muranaka-jun** [comment]
### MySQL
ユーザ作成とデータベース権限追加
```
mysql> select Host, User from mysql.user;
+-----------+---------------+
| Host      | User          |
+-----------+---------------+
| localhost | mysql.session |
| localhost | mysql.sys     |
| localhost | root          |
| localhost | wp_user1      |
+-----------+---------------+
4 rows in set (0.00 sec)

mysql> SHOW GRANTS for 'wp_user1'@'localhost';
+-----------------------------------------------------------------+
| Grants for wp_user1@localhost                                   |
+-----------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'wp_user1'@'localhost'                    |
| GRANT ALL PRIVILEGES ON `wordpress`.* TO 'wp_user1'@'localhost' |
+-----------------------------------------------------------------+
2 rows in set (0.00 sec)
```
wordpress データベース接続ユーザ変更
```
# pwd
/var/www/html/sample.com
# cat wp-config.php
~省略~
/** MySQL データベースのユーザー名 */
define('DB_USER', 'wp_user1');
```

**Comment by muranaka-jun** [comment]
### SSL証明書の設定 httpからhttpsにリダイレクト設定

```
[root@localhost conf.d]# cat default.conf
server {
    listen 443 ssl;
    server_name  localhost;
    root /var/www/html/sample.com;
    charset UTF-8;
    access_log  /var/log/nginx/sample.com.access.log  main;
    error_log /var/log/nginx/sample.com.error.log;

    location / {
        index  index.php index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    location ~ \.php$ {
        fastcgi_pass   unix:/var/run/php-fpm/php-fpm.sock;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }
    # 自己署名証明書
    ssl_certificate /etc/nginx/ssl/nginx.pem;
    # 暗号化鍵
    ssl_certificate_key /etc/nginx/ssl/nginx.key;
    # もしパスワードを入力したら追加（今回は省略）
    # ssl_password_file /etc/nginx/ssl/cert.password;
    # ...
}
[root@localhost conf.d]# 
```

**Comment by muranaka-jun** [comment]
### サイトの状態
<img width="431" alt="2018-11-19 20 10 55" src="https://user-images.githubusercontent.com/43940261/48703539-5a787400-ec37-11e8-8008-cc626a83c248.png">

**Comment by muranaka-jun** [comment]
### Nginx チューニング
変更箇所
```
# pwd
/etc/php-fpm.d
[root@localhost php-fpm.d]# cat www.conf
~省略~
pm.start_servers = 10
# 起動時のプロセス数
pm.min_spare_servers = 10
# 暇な時に残っているプロセス値の最小値
pm.max_spare_servers = 17
# 暇な時に残っているプロセス値の最大値
```
参考サイト
[](https://glorificatio.org/archives/3025)

**Comment by RVIRUS0817** [comment]
良いと思います！！
あとはローカルから適当なドメインを名前解決して、バーチャルの設定をしてみてください。
こちら完了しましたら同じ設定をansibleで自動化します。👍

**Comment by muranaka-jun** [comment]
### 名前解決
・ローカル環境
```
$ cat /etc/hosts
~省略~
192.168.33.10	vagrant01
```
### 公開鍵をサーバ登録
・ローカルからssh-copy-id を使用
```
$ ssh-copy-id vagrant@vagrant01
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/Users/muranakajun/.ssh/id_rsa.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
vagrant@vagrant01's password:

Number of key(s) added:        1

Now try logging into the machine, with:   "ssh 'vagrant@vagrant01'"
and check to make sure that only the key(s) you wanted were added.
```
### 公開鍵認証でログイン確認
```
$ ssh vagrant@vagrant01
Last login: Sun Nov 25 10:24:53 2018 from 10.0.2.2
Welcome to your Vagrant-built virtual machine.
[vagrant@vagrant01 ~]$
```

**Comment by muranaka-jun** [comment]
### IPではなく、バーチャルで名前解決
```
# cat /etc/nginx/conf.d/default.conf
~省略~
server {
       listen 80;
       server_name murajun.com;
}
```
![2018-12-01 11 31 33](https://user-images.githubusercontent.com/43940261/49323317-d7232080-f55c-11e8-9bd2-4418bd9df2d4.png)

**Comment by RVIRUS0817** [comment]
@muranaka-jun 
よいと思います！！！お疲れ様でした！！
